#leap-day
#theme: jekyll-theme-hacker
theme: jekyll-theme-minimal
title: MicroGP
description: A multi-purpose extensible self-adaptive evolutionary algorithm
logo: images/microgp.png
show_downloads: false
google_analytics: 28094298-6
